### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by Fred-Vatin** [j-hc/revanced-magisk-module#243]
My fork is updated.

## My config.toml

```toml
logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode= "module"       #'both', 'apk' or 'module'
# space-seperated patches to exclude (multiline strings are not supported)
excluded-patches= "always-autorepeat enable-debugging hide-info-cards hide-cast-button hide-autoplay-button hide-captions-button vanced-microg-support"
included-patches= ""       # space-seperated patches to include (non-excluded patches are included by default)
version= "18.19.35"        # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
exclusive-patches= false   # exclude all patches by default. default: false
apkmirror-dlurl= "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name= "ytrv-magisk"
```

## error
![Build Modules · Fred-Vatin¦revanced-magisk-module@1a2f8b8](https://github.com/j-hc/revanced-magisk-module/assets/22337329/0ae8aa07-fa8c-4748-b8ee-42727f4b273c)

## log
Here is the [full log](https://pipelines.actions.githubusercontent.com/serviceHosts/c74b3290-659f-4794-9bd3-e46ceb508554/_apis/pipelines/1/runs/50/signedlogcontent/2?urlExpires=2023-05-24T21%3A21%3A31.5865121Z&urlSigningMethod=HMACV1&urlSignature=mbBF3mgovae6GFnR9v8fqEVWdG3JdCko2son0xyUKPc%3D)

**Comment by j-hc** [comment]
why do you think this is a bug of revanced-magisk-module ? you opted out of using the recommended version (auto) and the reason why it failed is stated in red in the logs you shared.

**Comment by ramanveerji** [comment]
> why do you think this is a bug of revanced-magisk-module ? you opted out of using the recommended version (auto) and the reason why it failed is stated in red in the logs you shared.

even after setting auto, build is failing

**Comment by Fred-Vatin** [comment]
> why do you think this is a bug of revanced-magisk-module ?

Yes, it seems the integration patch is the culprit. Do you have the same error too ?

The revanced team updated their CLI and the file [build.gradle.kts](https://github.com/j-hc/revanced-cli/compare/main...revanced:revanced-cli:main#diff-c0dfa6bc7a8685217f70a860145fbdf416d449eaff052fa28352c5cec1a98c06) has been updated compared to your own CLI version. Could it cause the integration failure ?

---
I used the target version recommended by revanced team. I was not aware that the `auto` settings would download the same version. I will use it in future.
![image](https://github.com/j-hc/revanced-magisk-module/assets/22337329/f39002c0-4d40-4c26-85e8-f6eefe15e99b)

Using auto and not filling excluded-patches give me the exact same error.

```toml
logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode= "module"       #'both', 'apk' or 'module'
# space-seperated patches to exclude (multiline strings are not supported)
excluded-patches= ""
included-patches= ""       # space-seperated patches to include (non-excluded patches are included by default)
version= "auto"            # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
exclusive-patches= false   # exclude all patches by default. default: false
apkmirror-dlurl= "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name= "ytrv-magisk"
```
