### ISSUE TITLE
`Rvx` is not DEAD its now `ReX`

### ISSUE THREAD

**Issue by NormTurtle** [j-hc/revanced-magisk-module#295]
# ReVanced Extended is now **ADVANCED**  and very much _ALIVE_

dude named [YT-ADVANCED](https://github.com/YT-Advanced) made 
- [ReX-patches](https://github.com/YT-Advanced/ReX-patches)
- [ReX-integrations](https://github.com/YT-Advanced/ReX-integrations)

please consider adding them to BUILD and Configs with more options on customizations

**Comment by alsyundawy** [comment]
[Music-Extended] #
app-name = "Music"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "j-hc/revanced-cli"
rv-brand = "Music ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "both"


[YouTube-Extended] # 
app-name = "YouTube"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "j-hc/revanced-cli"
rv-brand = "YouTube ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

**Comment by NormTurtle** [comment]
bruh i litrally tried as u gave me the above `config.toml`
but its can't build it just **FAILS**
https://github.com/NormTurtle/revanced-magisk-module/actions/runs/5849178199
```toml
[YT-ReX]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "j-hc/revanced-cli"
rv-brand = "YouTube Advanced"
```
