### ISSUE TITLE
Any version supported on Android 7?

### ISSUE THREAD

**Issue by Ramys** [j-hc/revanced-magisk-module#426]
Hi..
Any version supported on Android 7?
Thanks.

**Comment by j-hc** [comment]
youtube versions for which revanced patches exists are not supported in android 7

**Comment by trmdi** [comment]
Try this `config.toml`:

```toml
[YouTube]
rv-brand = "rvx-android67"
build-mode = "apk"
patches-source = "kitadai31/revanced-patches-android6-7"
integrations-source = "kitadai31/revanced-integrations"
cli-source = "kitadai31/rvcli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
version = "17.34.36"
```
