### ISSUE TITLE
RVX patches crashes when built with rvmm

### ISSUE THREAD

**Issue by Fred-Vatin** [j-hc/revanced-magisk-module#545]
Hi, tried to install RVX youtube and music using this config with last commit 9b44264 from December 9:
```toml
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
# GLOBAL
rv-brand = "Revanced"

[Music-EX]
app-name = "Music"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[YouTube-EX]
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
excluded-patches = "'Theme' 'Alternative thumbnails' 'Enable debugging'"
```

Apps crash immediately. I cleaned up data via android settings and some revanced related files remained in `data/adb` after module deletion before reinstalling modules to no avail.

ROOT apk built with RVX manager work.
